### ISSUE TITLE
Update site is not accessible

### ISSUE THREAD

**Issue by EmergReanimator** [vgcpge/eclipse.copilot#11]
The [update site URL](https://vgcpge.github.io/eclipse.copilot/) is invalid: Error 404 not found.

**Comment by vgcpge** [comment]
Thanks. Looking into it.

**Comment by vgcpge** [comment]
Thanks for the report. Unfortunately I can't reproduce the problem:
<img width="791" alt="Screenshot 2023-06-09 at 21 20 50" src="https://github.com/vgcpge/eclipse.copilot/assets/129676242/df7442db-b1c3-4aef-bc88-61167f9ec9d9">
Try using it as an update site.
Reminder: update sites can't be viewed from a Web browser, they are to be used in [Help/Install New Software dialog in Eclipse](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-124.htm).

Please inform me if the update site is unusable from the "Install New Software"  dialog so I could reopen the issue.

**Comment by EmergReanimator** [comment]
> Reminder: update sites can't be viewed from a Web browser, they are to be used in [Help/Install New Software dialog in Eclipse](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-124.htm).
I see. I may confirm that it works correctly when accessed from eclipse.

Thanks for quick response!

**Comment by vgcpge** [comment]
Thank you for checking 👍

**Comment by vgcpge** [comment]
Next release will add a [disambiguation page](https://github.com/vgcpge/eclipse.copilot/blob/main/repository/index.html) in the update site.
