### ISSUE TITLE
Plugin unable to resolve domain name through corporate proxy

### ISSUE THREAD

**Issue by tyunta** [vgcpge/eclipse.copilot#16]
Hello,

I am working in an environment where internet access is routed through a corporate proxy. Unfortunately, I encountered a problem when using this plugin; it seems unable to resolve the domain name for GitHub, resulting in an error.

Eclipse allows the configuration of proxy information. I propose enhancing this plugin to use that information to connect to GitHub. This could assist users like me who are working behind a company's proxy.

I look forward to your response.

Best regards,
Tyunta

**Comment by vgcpge** [comment]
@tyunta idea is good. I don't know if it is possible. Do you have any official Copilot integrations working in your environment?

**Comment by tyunta** [comment]
@vgcpge Yes, that's correct. I have confirmed that the official Copilot is functioning on neovim and Visual Studio Code on Ubuntu 22.04. In neovim, I have been able to connect via a proxy by configuring the 'g:copilot_proxy' setting, as detailed at the URL below. However, even with this setting enabled, the plugin cannot connect via the proxy.

https://github.com/github/copilot.vim/blob/release/doc/copilot.txt

**Comment by vgcpge** [comment]
> In neovim, I have been able to connect via a proxy by configuring the 'g:copilot_proxy' setting, as detailed at the URL below.

Nice, I will take a look at implementation for Neovim.
> However, even with this setting enabled, the plugin cannot connect via the proxy.

Yes. Eclipse integration does not use Neovim settings.

**Comment by vgcpge** [comment]
@tyunta does your proxy require authentication? Does it perform MitM attack?

**Comment by vgcpge** [comment]
@tyunta I have a prototype solution ready. Please try it out by updating from an [unsigned update site archive](https://github.com/vgcpge/eclipse.copilot/suites/13679170480/artifacts/755889079)
<sub>The link is an archived update site, unusable directly.  Download it and point the install dialog to the downloaded file.</sub>

**Comment by vgcpge** [comment]
The solution is merged in the main branch and will be available in the next release. Current build of master branch can be tested with an [archived update site](https://github.com/vgcpge/eclipse.copilot/suites/13685916047/artifacts/756431582).

**Comment by tyunta** [comment]
@vgcpge 

Thank you. It works great.
I verified that communication through proxies is possible and that connections are possible even with proxies that require authentication.
In the case of Ubuntu, I had to set http_proxy and https_proxy as environment variables instead of starting Eclipse directly. This could be due to the fact that Eclipse's proxy settings read the Native provider's settings, so it is better to reflect the proxy settings selected in Active Provider.
A log is output to the console indicating that access to telemetry has failed, but this does not affect the operation of the plugin.

Apologies for the delay in replying.

**Comment by wolfJaeger** [comment]
Thank you very much!
I verified the communication i an win10 environment, where i have installed my eclipse inside wsl2. It works!

**Comment by vgcpge** [comment]
@tyunta I do not understand the situation with Active provider setting you describe. Have you tried Manual Active provider like on the following screenshot?
<img width="651" alt="Screenshot 2023-06-21 at 12 11 58" src="https://github.com/vgcpge/eclipse.copilot/assets/129676242/5c1f34fb-bd1e-4082-b9c4-84db1c0c1ada">

AFAIK the Direct provider is not suitable for manual configuration.

While Eclipse logs warnings about mismatch of preferences proxy settings and environment, I expect it to use preferences anyway.

**Comment by vgcpge** [comment]
@tyunta 
> A log is output to the console indicating that access to telemetry has failed, but this does not affect the operation of the plugin. 

The telemetry stuff is highly suspicious, but I will probably ignore it until there are explicit complaints. Is it logged as an Error or as a Warning in Error Log view?
