### ISSUE TITLE
Unofficial specs for Github Copilot plugin-agent.js interactions

### ISSUE THREAD

**Issue by haukot** [vgcpge/eclipse.copilot#18]
HI! I've done research and reverse-engineered the Github Copilot protocol between IDE plugin and agent.js, and have tried to document it. This is based on Github Copilot plugin version for JetBrains and some parts of agent.js. You can see the specs in this repo https://github.com/haukot/copilot_specifications
Hope this could help in plugin development!

**Comment by vgcpge** [comment]
Thanks. This might be useful for new features. (No features are planned at the moment).

**Comment by vgcpge** [comment]
@haukot you are already quite invested. Making a PR or two is not much more effort, is it? 😉

**Comment by vgcpge** [comment]
@haukot do you happen to know what version of Node.js are compatible with Copilot and how are they managed/accessed from it? Official installation documentation says Node 17, but Node 19 and 20 work just fine for me. Also, do you have any insight on how VSCode extension launches same code as agent.js? I'm asking, as #5 is still unsolved.

**Comment by haukot** [comment]
> @haukot you are already quite invested. Making a PR or two is not much more effort, is it? wink

Sure, but I'm using emacs, and will contribute to that plugin :)

>do you happen to know what version of Node.js are compatible with Copilot and how are they managed/accessed from it? 

I don't know about minimal node requirements.
VS Code plugin runs in many ways the same code as inside agent.js. So the node version could be the same as it possible with VS Code.
As I understand, agent.js and extension.js(which is used by VS Code extension) are using the same codebase, just with different build process. So the core is the same, but agent.js has interfaces for plugin, and extension.js works on direct event listeners from VS Code.

Another way - you can check which packages are used in agent.js, and check node version by their requirements. For that, search by e.g. `"ts-node"` in the file https://github.com/github/copilot.vim/blob/release/copilot/dist/agent.js
