### ISSUE TITLE
Eclipse plugin link is dead

### ISSUE THREAD

**Issue by jareid** [vgcpge/eclipse.copilot#19]
The link in your README.md is dead (produces a 404) - https://vgcpge.github.io/eclipse.copilot/

**Comment by vgcpge** [comment]
Duplicates https://github.com/vgcpge/eclipse.copilot/issues/11

**Comment by jareid** [comment]
Thanks for quick response. Sorry for not checking previous issues. Also willing to contribute if you need help :)
