### ISSUE TITLE
Does not provide support for CDT (C/C++) file types

### ISSUE THREAD

**Issue by AMD-aric** [vgcpge/eclipse.copilot#21]
It would be amazing if this also hooked up to C/C++ file types.
Currently no Language Server Proposal option appears under C/C++ > Editor > Content Assist > Advanced.

**Comment by vgcpge** [comment]
Such support is out of scope for this project. Consider alternatives:

- Use [Eclipse CDT LSP](https://github.com/eclipse-cdt/cdt-lsp) and tell us
about the experience.
- Request LSP4E content assist feature from CDT project or write one yourself.
- Open C files in Generic Text Editor
