### ISSUE TITLE
 Issues with Neovim's Copilot Plugin version 1.9.x

### ISSUE THREAD

**Issue by sosuisen** [vgcpge/eclipse.copilot#23]
Copilot for Neovim (https://github.com/github/copilot.vim.git) does not work anymore with this integration, probably because the directory structure has changed since v1.9. You need to use v1.8.4 for it to work.

"copilot/dist" has been changed to just "dist".

Verified on Windows.

**Comment by vgcpge** [comment]
Thank you for the report.
As a workaround, use Preferences/Language Server/Copilot to configure arbitrary agent location.
See #5.

**Comment by vgcpge** [comment]
@sosuisen I've prepared a fix in #24. Does the [archived update site built there](https://github.com/vgcpge/eclipse.copilot/suites/14043345062/artifacts/784448421) fix the problem for you?

**Comment by vgcpge** [comment]
The fix is released in version 0.0.15
