### ISSUE TITLE
Failed to read root certificates on Windows

### ISSUE THREAD

**Issue by vgcpge** [vgcpge/eclipse.copilot#30]
On Windows, Copilot fails to produce any completions, logs following warning and hangs.

```
[Warning]	[WARN] [certificates] [2023-07-17T18:44:48.642Z] Failed to read root certificates: Error: ENOENT: no such file or directory, copyfile '%USERPROFILE%\eclipse\ide-latest\eclipse\configuration\org.vgcpge.eclipse.copilot.ui\downloaded-agent\copilot.vim-release\dist\roots.exe' -> 'C:\Users\VASILI~1\AppData\Local\Temp\copilot-y0jtIC\copilot-find-certificates.exe'
```

**Comment by vgcpge** [comment]
This is not a fatal bug, just a warning. Once Copilot is configured using nvim, it works fine in plugin but keeps logging this warning.

**Comment by getthegroove** [comment]
Hey I tried using your plugin but I keep getting the error above. I followed your hint and installed neovim and the corresponding copilot plugin. It works fine in nvim but the eclipse plugin still fails. Any advise?

**Comment by vgcpge** [comment]
@getthegroove attach Error Log.

The only time I got problems on Windows is when I [used incompatible Node.js version](https://github.com/vgcpge/eclipse.copilot/issues/31) (18). The message in original description is just a warning and is not causing problems by itself. But when running on Node.js 18, it is printed in error output and seem to terminate/hang Copilot agent.

**Comment by getthegroove** [comment]
Here you are!

[copilot.log](https://github.com/vgcpge/eclipse.copilot/files/12257466/copilot.log)

**Comment by getthegroove** [comment]
> The only time I got problems on Windows is when I [used incompatible Node.js version](https://github.com/vgcpge/eclipse.copilot/issues/31) (18). The message in original description is just a warning and is not causing problems by itself. But when running on Node.js 18, it is printed in error output and seem to terminate/hang Copilot agent.

I'm running Node.js 20.5.0

**Comment by vgcpge** [comment]
> [copilot.log](https://github.com/vgcpge/eclipse.copilot/files/12257466/copilot.log)

This is not an [error log](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Freference%2Fref-error_log_view.htm). Looks like a protocol dump. How do you collect it?

**Comment by vgcpge** [comment]
Please provide Error Log and reopen.
