### ISSUE TITLE
Installation for Eclipse 2023-9

### ISSUE THREAD

**Issue by dnolte123** [vgcpge/eclipse.copilot#32]
Installed fresh Eclipse 2023-9
Installed plugin from https://vgcpge.github.io/eclipse.copilot/
Opened Text file with generic Text Editor - no prompt for Device Activation appears..
Plugin seems not to work

**Comment by dnolte123** [comment]
With the Java Editor the second hint windows appear - is Device Activation not necessary any more

**Comment by vgcpge** [comment]
AFAIK, device activation is still necessary. 
@dnolte123 please, [export Error Log](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Freference%2Fref-error_log_view.htm) and attach it here.

**Comment by vgcpge** [comment]
Please reopen when more information is available (including Error Log).
