### ISSUE TITLE
Node.js embedded missing from Usage

### ISSUE THREAD

**Issue by moshidev** [vgcpge/eclipse.copilot#34]
Hi, thanks for making this repo and making it open source :)
It has been pretty helpful all along.

At the README.md#Usage section it is missing the first step: Installing the Node.js embedded plugin. It is present at your video, but I think it will be helpful to have it at those steps too.

**Comment by vgcpge** [comment]
Thanks.
Embedded Node.js has version 18 which proven to be unstable on some platforms and had to be removed from documentation. It works fine most of the time, but when it fails, it is very hard to diagnose.

**Comment by moshidev** [comment]
I see, that's the reason. When I tried to install the plugin an error along the lines appeared: can't satisfy osgi; org.eclipse.jdt.annotation "1.0.0". Installing the Node.js embedded plugin solved that issue.

**Comment by vgcpge** [comment]
This is interesting.

Have you checked "Contact all update sites..." item in installation dialog? It is required.
If installation fails with it checked, could you create a bug?

**Comment by moshidev** [comment]
I did. Don't know if it could be related, I'm using e2 studio from Renesas.

```
Renesas e² studio

Version: 2023-07 (23.7.0)
Build Id: R20230714-1443

Parts Copyright (C) 2010-2023 Renesas Electronics Corp.
All rights reserved.

e² studio IDE is an extension of software developed for
eclipse.org.

e² studio IDE is based on Eclipse Platform 4.27 (2023-03)
and CDT version 11.1.1.
```

**Comment by vgcpge** [comment]
This custom product may modify Availablle Update sites preference. Could you list those? Is there download.eclipse.org in the list?

**Comment by moshidev** [comment]
Enabled ones are those which came with e2 studio. Non-enabled those which I added after.

![Screenshot 2023-10-01 at 11 31 48](https://github.com/vgcpge/eclipse.copilot/assets/46326833/f9a50595-7d6a-44bc-9130-b728eacf7b64)

**Comment by vgcpge** [comment]
Eclipse Repository is usually required, studio missing it would explain the problem.
I could try including Eclipse update site in the plugin distribution,  but that has nasty side-effects, so this error will have to stay.

Documentation will have to be updated though. Thanks for bringing the problem up.
