### ISSUE TITLE
Enable for C editor

### ISSUE THREAD

**Issue by cldhms** [vgcpge/eclipse.copilot#36]
The readme states that it should be possible to use the plugin for any language. But how do I enable it for C code? The language servers only lists "Java Source File" and "Text" and I don't find an easy way to add additional content types without editing the plugin itself.

**Comment by vgcpge** [comment]
"Any other editor supporting the standard APIs" does not mean there is a suitable editor for a given language. Note that any text based language is editable with "Generic Text Editor".
I do not know how to enable language server support for CDT, but consider checking out following projects:

- [GSoC 2018 - Eclipse CDT: Integration with the Language Server Protocol](https://gist.github.com/ManishKhurana11/f940b82c8cebe04ee1bb91ebb2ac861d#gsoc-2018---eclipse-cdt-integration-with-the-language-server-protocol) 
- LSP4E-CPP

To be fair at a first glance both are dead.
