### ISSUE TITLE
Allow to skip GitHub registration (with device code)

### ISSUE THREAD

**Issue by kwin** [vgcpge/eclipse.copilot#37]
I want to ship this plugin in a distribution to a large user base. Not everyone has access to Copilot yet. Therefore it would be beneficial if there would be an easy way to cancel the first time registration with GitHub and allow to explicitly call that manually (e.g. from `Language Servers`->`Copilot`).

**Comment by vgcpge** [comment]
Consider shipping with Copilot LSP disabled. See Preferences/Language Servers. Preferences are customizable with `plugin_customization.ini`. Please reopen if this does not work for your usecase.
