### ISSUE TITLE
Add some keywords to the preference page

### ISSUE THREAD

**Issue by kwin** [vgcpge/eclipse.copilot#38]
The preference page at https://github.com/vgcpge/eclipse.copilot/blob/08c692e9436b436bc367453fddb32a6856e8ea00/org.vgcpge.eclipse.copilot.ui/plugin.xml#L31C14-L31C14 should have some keywords associated to ease finding it via search:

- LSP
- Language Servers
- Language Server Protocol
- Github

The approach for that is described in https://stackoverflow.com/a/31449146/5155923.

**Comment by vgcpge** [comment]
While this may seem useful, I have following objections:

1. LSP, Language Servers, Language Server Protocol should find the parent page of LSP4E, Copilot page would be too specific for that search
2. I was trying to avoid using trademarked words in UI, so Github keyword not an option.

Please suggest other options or legal advice and reopen the issue.
