### ISSUE TITLE
Not signed in even when signed in

### ISSUE THREAD

**Issue by TRT-SOCOMEC** [vgcpge/eclipse.copilot#40]
Hello, 
I get an error saying that I'm not signed in just after I signed and try to use CTRL+SPACE.

Here is the log :

```
[2023-11-17T11:00:22.010166100+01:00] LANGUAGE_SERVER_TO_LSP4E org.vgcpge.eclipse.copilot.ui.copilot:
{"jsonrpc":"2.0","id":"2","method":"window/showMessageRequest","params":{"actions":[{"title":"OK"},{"title":"Cancel"}],"type":2,"message":"To sign in Github Copilot, enter code XXX-XXX on https://github.com/login/device?userCode\u003dXXX-XXX. For your convenience code has been appended to the URL."}}

[2023-11-17T11:00:37.101538600+01:00] LSP4E_TO_LANGUAGE_SERVER org.vgcpge.eclipse.copilot.ui.copilot:
Content-Length: 50



[2023-11-17T11:00:37.103530100+01:00] LSP4E_TO_LANGUAGE_SERVER org.vgcpge.eclipse.copilot.ui.copilot:
{"jsonrpc":"2.0","id":"2","result":{"title":"OK"}}

[2023-11-17T11:01:40.640849400+01:00] LSP4E_TO_LANGUAGE_SERVER org.vgcpge.eclipse.copilot.ui.copilot:
Content-Length: 311



[2023-11-17T11:01:40.643842200+01:00] LSP4E_TO_LANGUAGE_SERVER org.vgcpge.eclipse.copilot.ui.copilot:
{"jsonrpc":"2.0","id":"2","method":"textDocument/completion","params":{"context":{"triggerKind":1},"textDocument":{"uri":"file:///C:/Users/TRT/DevJalios/workspace/jcms/WebContent/WEB-INF/classes/eu/capcod/jcmsplugin/importmllivelinkplugin/handlers/MlImportHandler.java"},"position":{"line":269,"character":65}}}

[2023-11-17T11:01:40.657803500+01:00] LANGUAGE_SERVER_TO_LSP4E org.vgcpge.eclipse.copilot.ui.copilot:
{"jsonrpc":"2.0","id":"2","error":{"code":1000,"message":"Not authenticated: NotSignedIn"}}

[2023-11-17T11:01:43.636562400+01:00] LSP4E_TO_LANGUAGE_SERVER org.vgcpge.eclipse.copilot.ui.copilot:
Content-Length: 311



[2023-11-17T11:01:43.638599200+01:00] LSP4E_TO_LANGUAGE_SERVER org.vgcpge.eclipse.copilot.ui.copilot:
{"jsonrpc":"2.0","id":"3","method":"textDocument/completion","params":{"context":{"triggerKind":1},"textDocument":{"uri":"file:///C:/Users/TRT/DevJalios/workspace/jcms/WebContent/WEB-INF/classes/eu/capcod/jcmsplugin/importmllivelinkplugin/handlers/MlImportHandler.java"},"position":{"line":269,"character":65}}}

[2023-11-17T11:01:43.643538700+01:00] LANGUAGE_SERVER_TO_LSP4E org.vgcpge.eclipse.copilot.ui.copilot:
{"jsonrpc":"2.0","id":"3","error":{"code":1000,"message":"Not authenticated: NotSignedIn"}}
```

**Comment by vgcpge** [comment]
This is likely a known problem with error caching. Happens on first request for completions, should not happen on a second (different) request.

Try:
- edit the document and request completion again like in https://youtu.be/B_QZao3abBw?si=cwheOwVF-X1kFd70&t=79
- restart Eclipse

If nothing helps, attach the [error log](https://www.ibm.com/support/pages/how-export-eclipse-log-file).

**Comment by TRT-SOCOMEC** [comment]
Thanks for your help but I still got the error.

See linked log file for detail.
[error.log](https://github.com/vgcpge/eclipse.copilot/files/13391655/error.log)

**Comment by vgcpge** [comment]
The log has failed to upload, please update the message with an attachment.

**Comment by TRT-SOCOMEC** [comment]
Edited the post with the file !

**Comment by vgcpge** [comment]
Welp, I'm not sure what's going on. The protocol might have changed. As I'm  not eating the dogfood for now, this will take time to fix. Meanwhile consider alternatives: 

- https://github.com/equodev/eclipse-ai-example
- https://codeium.com/eclipse_tutorial

**Comment by TRT-SOCOMEC** [comment]
> Welp, I'm not sure what's going on. The protocol might have changed. As I'm not eating the dogfood for now, this will take time to fix. Meanwhile consider alternatives:
> 
> * https://github.com/equodev/eclipse-ai-example
> * https://codeium.com/eclipse_tutorial

Thank you for your help ! 
Will follow your project closely, take your time ! :)

**Comment by vgcpge** [comment]
I've managed to reproduce the problem in two ways:

1. Fail to complete the authentication process in browser. There are quite a few steps, and user can only continue to Eclipse after reaching https://github.com/login/device/success page.
2. Close Eclipse immediately after completion of authentication process. Then Copilot agent fails to store the authentication key in ~/.config/github-copilot/hosts.json and request reauthentication after Eclipse is restarted

I recommend to try again, but:
- ensure only one Eclipse process is running at the same time on the workstation
- make a pause of 15 seconds after each step
- capture screenshot of the authentication dialog and wipe out the key
- capture screenshots of each browser page and wipe out sensitive information
- after authentication is complete wait and see if hosts.json appears in the home directory(I don't remember exact Windows path)

If this attempt fails, try using Visual Studio Code or Neovim and see if the problem is reproducible with those. If these other tools work, attach screenshots captured above.

**Comment by TRT-SOCOMEC** [comment]
> I've managed to reproduce the problem in two ways:
> 
> 1. Fail to complete the authentication process in browser. There are quite a few steps, and user can only continue to Eclipse after reaching https://github.com/login/device/success page.
> 2. Close Eclipse immediately after completion of authentication process. Then Copilot agent fails to store the authentication key in ~/.config/github-copilot/hosts.json and request reauthentication after Eclipse is restarted
> 
> I recommend to try again, but:
> 
> * ensure only one Eclipse process is running at the same time on the workstation
> * make a pause of 15 seconds after each step
> * capture screenshot of the authentication dialog and wipe out the key
> * capture screenshots of each browser page and wipe out sensitive information
> * after authentication is complete wait and see if hosts.json appears in the home directory(I don't remember exact Windows path)
> 
> If this attempt fails, try using Visual Studio Code or Neovim and see if the problem is reproducible with those. If these other tools work, attach screenshots captured above.

Well, it seems I can't find the hosts.json file.
This maybe is the cause au the problem.

However even when logging in and not closing Eclipse, I'm not getting signed in.
