### ISSUE TITLE
NPE in Authentication.ensureAuthenticated

### ISSUE THREAD

**Issue by hb91546** [vgcpge/eclipse.copilot#41]
!ENTRY org.eclipse.lsp4e 1 0 2024-01-10 16:00:06.935
!MESSAGE [Log]	[DEBUG] [agent] [2024-01-10T22:00:06.922Z] Agent service starting

!ENTRY org.eclipse.lsp4e 1 0 2024-01-10 16:00:07.049
!MESSAGE [Log]	[DEBUG] [agent] [2024-01-10T22:00:07.039Z] Telemetry initialized

!ENTRY org.eclipse.lsp4e 1 0 2024-01-10 16:00:07.466
!MESSAGE [Info]	[INFO] [auth] [2024-01-10T22:00:07.463Z] Invalid copilot token: missing token: 403 

!ENTRY org.eclipse.lsp4e 4 0 2024-01-10 13:42:34.605
!MESSAGE [Error]	java.lang.NullPointerException: Cannot invoke "org.vgcpge.copilot.ls.rpc.Status.ordinal()" because "status" is null
	at org.vgcpge.copilot.ls.Authentication.ensureAuthenticated(Authentication.java:37)
	at org.vgcpge.copilot.ls.Authentication.<init>(Authentication.java:29)
	at org.vgcpge.copilot.ls.LanguageServer.lambda$1(LanguageServer.java:70)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)

**Comment by hb91546** [comment]
Is there a way to reauthenticate as another user that has Copilot access?  
![image](https://github.com/vgcpge/eclipse.copilot/assets/2519865/2720ed64-5abe-47ca-9bb7-648fd5d83115)

**Comment by basilevs** [comment]
> Is there a way to reauthenticate as another user that has Copilot access?

No sign-out function is implemented in the plugin itself, but if file  `~/.config/github-copilot/hosts.json` is deleted, the authentication is reset and relogin will happen automatically. I would suggest to:

- Exit Eclipse
- Delete the file
- Restart Eclipse
