### ISSUE TITLE
Integrating lsp-server that runs locally

### ISSUE THREAD

**Issue by 4veg0s** [vgcpge/eclipse.copilot#43]
Hello there! This project seems like the promising one, yet I struggle to make it work (I've got issues with GitHub's Copilot). However, I have my own server running in local network that does completions in VS Code and IntelliJ. So, could you please give me a clue whether it is somehow possible to communicate with my local server instead of GitHub's remote one? Would really appreciate your feedback

**Comment by vgcpge** [comment]
You don't need this project to use your local language server. Use [Eclipse LSP4E - Language Server Protocol client for Eclipse IDE](https://github.com/eclipse/lsp4e) instead.
