### ISSUE TITLE
Automate installation of the official backend

### ISSUE THREAD

**Issue by vgcpge** [vgcpge/eclipse.copilot#5]
Users have to download or checkout Neovim's integration manually. This process is inconvenient and defeats the illusion of self-sufficient plug-in.
It may be nice to automate the download.

**Comment by vgcpge** [comment]
On a second thought, users also need to install an appropriate Node.js, and it might be strange to install one, but not another dependency.

**Comment by AntipodTX** [comment]
By the README i do not need to have Neovim installed, so from the instructions on the attached link (https://docs.github.com/en/copilot/getting-started-with-github-copilot?tool=neovim#installing-the-neovim-extension-on-windows) i can only do the first step, and of course, when i go to the eclipse, nothing works

**Comment by vgcpge** [comment]
> By the README i do not need to have Neovim installed, so from the instructions on the attached link (https://docs.github.com/en/copilot/getting-started-with-github-copilot?tool=neovim#installing-the-neovim-extension-on-windows) i can only do the first step, and of course, when i go to the eclipse, nothing works

This project takes Copilot agent from the same directory as Neovim ($HOME/AppData/Local/nvim/pack/github/start/copilot.vim). Authentication is done in Eclipse, so Neovim's setup steps like `:Copilot setup`  should not be needed. If you follow installation instructions and experience problems,  please create a separate issue. Make sure to include steps to reproduce, error log,  actual and expected results.

**Comment by vgcpge** [comment]
Node.js is distributed with Eclipse in `org.eclipse.wildwebdeveloper.embedder.node` plugin.
It is deployed in`<installation directory>/.node`

**Comment by vgcpge** [comment]
The plugin now detects Wild Web Developer Embedded Node.js and provides a way to explicitly specify Node.js executable via preferences. This significantly reduces the need for manual installation of Node.js, as Wild Web developer is included in many Eclipse products.
This makes automated installation of Copilot's backend more appealing.

**Comment by vgcpge** [comment]
When no user-installed instances of Copilot agent are found, plugin downloads one itself.
